apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-todo-app
  template:
    metadata:
      labels:
        app: my-todo-app
    spec:
      containers:
      - name: my-todo-app
        image: sampathsai/my-todo-app:latest
        ports:
        - containerPort: 80
